events {}

http {
    server {
        listen 80;
        server_name lovestonedgirls.dam;
        location / {
            proxy_pass http://ecommerce:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;
        server_name admin.lovestonedgirls.dam;
        location / {
            proxy_pass http://admin:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;
        server_name api.lovestonedgirls.dam;
        location / {
            proxy_pass http://api:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
